### ISSUE TITLE
How do I Delete A database??

### ISSUE THREAD

**Issue by abizit** [mdbootstrap/MDB-Angular-PWA#1]
I tried you app, Works perfectly. But how do I delete a Database?

**Comment by Bloodcast69** [comment]
@abizit What do you mean by deleting a database? Do you want to delete all records from this app from your local storage? 

Please take a look at one of these links:
- https://mage2.pro/t/topic/1659
- https://stackoverflow.com/questions/6084099/how-to-view-delete-local-storage-in-firefox
